[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "config.js"

[[headers]]
  for = "/config.js"
  [headers.values]
    Cache-Control = "no-cache"
